definitions:
  models.Weather:
    properties:
      date:
        type: string
      location:
        type: string
      temperatureC:
        type: string
    type: object
info:
  contact: {}
  description: API template
  title: XXX API
  version: "1.0"
paths:
  /api/weather:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Weather'
            type: array
      summary: Find all weather info
      tags:
      - Weathers
swagger: "2.0"
